id: AE64B6F7F
title: The Foundation of All Qualities
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:56:36.238291
  last_modified_at: 2022-03-01 01:56:36.238295
