id: AE64B6F7F
title: Short Guru Yoga of the Noble Lord, All-Knowing Tsongkhapa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:56:36.235043
  last_modified_at: 2022-03-01 01:56:36.235046
